// @/lib/form-config.ts

export const meioOptions = [
    { value: "", label: "Aguardando PI..." },
    { value: "AS", label: "Assessoria de Imprensa" },
    { value: "AT", label: "Ativação" },
    { value: "BD", label: "Busdoor" },
    { value: "BP", label: "Produção Busdoor" },
    { value: "BR", label: "Brinde" },
    { value: "BV", label: "Bonificação de Volume" },
    { value: "CA", label: "Cachê de Modelo" },
    { value: "CI", label: "Cinema" },
    { value: "CN", label: "Cinema" },
    { value: "CP", label: "Produção Cinema" },
    { value: "CR", label: "Criação / Adaptação" },
    { value: "CS", label: "Carro de Som" },
    { value: "DE", label: "Despesa" },
    { value: "DO", label: "Digital Out of Home" },
    { value: "EP", label: "Produção Mídia Externa" },
    { value: "EV", label: "Promoção/Eventos" },
    { value: "FE", label: "FEE MÍDIA" },
    { value: "FI", label: "Fidelidade" },
    { value: "FL", label: "Front Light" },
    { value: "FO", label: "Fotógrafo" },
    { value: "FP", label: "FreeLancer Pesquisa" },
    { value: "FT", label: "Fotolito" },
    { value: "GD", label: "Gigadoor" },
    { value: "GO", label: "Gráfica Off-Set" },
    { value: "GS", label: "Gráfica Serigrafia" },
    { value: "IA", label: "Internet-Audio" },
    { value: "IB", label: "Internet-Busca" },
    { value: "ID", label: "Internet-Display e outros" },
    { value: "IL", label: "Ilustrador" },
    { value: "IN", label: "Internet" },
    { value: "IP", label: "Instituto de Pesquisa" },
    { value: "IS", label: "Internet-Social" },
    { value: "IV", label: "Internet-Video" },
    { value: "JN", label: "Jornal" },
    { value: "LO", label: "Locação Áudio e Vídeo" },
    { value: "MA", label: "Mídia Alternativa" },
    { value: "MD", label: "Mala Direta" },
    { value: "ME", label: "Mídia Externa" },
    { value: "MI", label: "Material de Informática" },
    { value: "ML", label: "Material de Limpeza" },
    { value: "MN", label: "Mídia Interna" },
    { value: "MO", label: "Material de Escritório" },
    { value: "MS", label: "Mídia Social" },
    { value: "MT", label: "Metrô" },
    { value: "OD", label: "Outdoor" },
    { value: "OU", label: "Outros" },
    { value: "PA", label: "Prod. Áudio" },
    { value: "PB", label: "Produção de Mala Direta" },
    { value: "PC", label: "Prod. Computação" },
    { value: "PD", label: "Produção Rádio" },
    { value: "PF", label: "Produção Frontlight" },
    { value: "PH", label: "Produção Dooh" },
    { value: "PI", label: "Produção Mídia Interna" },
    { value: "PJ", label: "Produção Jornal" },
    { value: "PM", label: "Produção Metrô" },
    { value: "PN", label: "Produção Internet" },
    { value: "PO", label: "Produção Outdoor" },
    { value: "PQ", label: "Pesquisa de Mercado" },
    { value: "PS", label: "Produção de Revista" },
    { value: "PT", label: "Produção TV" },
    { value: "PV", label: "Prod. VT/Filme" },
    { value: "PW", label: "Produção de Internet" },
    { value: "PY", label: "Produção/Material Ativação" },
    { value: "RA", label: "Rádio AM" },
    { value: "RD", label: "Rádio" },
    { value: "RE", label: "Revista" },
    { value: "RF", label: "Rádio FM" },
    { value: "RL", label: "Relações Públicas" },
    { value: "RP", label: "Representante" },
    { value: "RT", label: "Reserva Técnica" },
    { value: "TA", label: "TV Assinatura" },
    { value: "TO", label: "Tailor Operações" },
    { value: "TR", label: "Tradutor" },
    { value: "TV", label: "Televisão" },
    { value: "VE", label: "Venda de Espaço" },
];

interface UploadGroup {
    name: string;
    label: string;
    meios: string[];
    accept: string;
}

export const uploadGroupsConfig: UploadGroup[] = [
    { name: "relatorio_fotografico_do", label: "Relatório Fotográfico de Todos os Pontos *", meios: ["DO"], accept: "image/*,.pdf,.zip" },
    { name: "relatorio_exibicoes_do", label: "Relatório de Exibições Automatizado *", meios: ["DO"], accept: ".pdf,.xlsx,.xls,.csv" },
    { name: "video_diurno_do", label: "Vídeo Diurno *", meios: ["DO"], accept: "video/*" },
    { name: "relatorio_enderecos_me", label: "Relatório com Endereço dos Pontos *", meios: ["ME"], accept: ".pdf,.xlsx,.xls,.csv" },
    { name: "fotos_pontos_me", label: "Fotos Diurnas (Amostrais) / Noturnas (se iluminado) *", meios: ["ME"], accept: "image/*,.zip" },
    { name: "relatorio_estacoes_mo", label: "Relatório com Listagem de Estações/Linhas/Carros *", meios: ["MT"], accept: ".pdf,.xlsx,.xls,.csv" },
    { name: "fotos_videos_mo", label: "Fotos ou Vídeos (Amostrais) *", meios: ["MT"], accept: "image/*,video/*,.zip" },
    { name: "comprovante_bd", label: "Relatório Fotográfico de Todos os Ônibus/Carros *", meios: ["BD"], accept: "image/*,.pdf,.zip" },
    { name: "comprovante_od", label: "Relatório Fotográfico com Endereço (Diurno/Noturno se iluminado) *", meios: ["OD"], accept: "image/*,.pdf,.zip" },
    { name: "comprovante_fl", label: "Relatório Fotográfico com Endereço (Diurno/Noturno se iluminado) *", meios: ["FL"], accept: "image/*,.pdf,.zip" },
    { name: "comprovante_mi_nf", label: "Nota Fiscal (Material de Informática) *", meios: ["MI"], accept: ".pdf,image/*" },
    { name: "comprovante_ml_nf", label: "Nota Fiscal (Material de Limpeza) *", meios: ["ML"], accept: ".pdf,image/*" },
    { name: "comprovante_mo_nf", label: "Nota Fiscal (Material de Escritório) *", meios: ["MO"], accept: ".pdf,image/*" },
    { name: "comprovante_mn", label: "Relatório Fotográfico de Todos os Pontos e Relação de Locais *", meios: ["MN"], accept: "image/*,.pdf,.zip" },
    { name: "comprovante_radio", label: "Relatório de Veiculação / Em caso de ações de blitz, enviar ZIP com fotos e/ou vídeo *", meios: ["RD", "RF", "RA"], accept: ".pdf,.xlsx,.xls,.csv,.zip,image/*,video/*" },
    { name: "comprovante_cinema", label: "Relatório de Exibição (Complexo, Número de Salas, Praça) *", meios: ["CI", "CN"], accept: ".pdf,.xlsx,.xls,.csv" },
    { name: "comprovante_impresso", label: "Material Físico (preferencialmente) + PDF/Foto do Título com Material Veiculado *", meios: ["JN", "RE"], accept: "image/*,.pdf" },
    { name: "comprovante_ativacao", label: "Relatório Fotográfico ou Vídeos + Detalhamento das Ações *", meios: ["AT"], accept: "image/*,video/*,.pdf,.zip" },
    { name: "comprovante_tv", label: "Relatório de Veiculação Automatizado *", meios: ["TV", "TA"], accept: ".pdf,.xlsx,.xls,.csv" },
    { name: "comprovante_internet", label: "Relatório de Veiculação + Prints das Peças *", meios: ["IN", "IA", "IB", "ID", "IS", "IV", "MS"], accept: "image/*,.pdf,.xlsx,.xls,.csv,.zip" },
    { name: "comprovante_brinde", label: "Nota Fiscal + Fotos dos Produtos *", meios: ["BR", "BV"], accept: "image/*,.pdf" },
    { name: "comprovante_despesa", label: "Nota Fiscal / Recibo *", meios: ["DE", "FE", "RT", "VE"], accept: ".pdf,image/*" },
    { name: "comprovante_evento", label: "Relatório Fotográfico + Detalhamento das Ações *", meios: ["EV"], accept: "image/*,video/*,.pdf,.zip" },
    { name: "comprovante_producao", label: "Nota Fiscal + Arquivos Produzidos *", meios: ["PA", "PC", "PD", "PV", "PY", "BP", "CP", "EP", "PF", "PH", "PI", "PJ", "PM", "PN", "PO", "PS", "PT", "PW", "PB"], accept: ".pdf,image/*,video/*,audio/*,.zip" },
    { name: "comprovante_grafica", label: "Nota Fiscal + Fotos do Material Impresso *", meios: ["GO", "GS", "FT"], accept: ".pdf,image/*" },
    { name: "comprovante_profissional", label: "Recibo / Nota Fiscal + Trabalho Executado *", meios: ["FO", "IL", "CA", "TR", "FP", "RP"], accept: ".pdf,image/*,.zip" },
    { name: "comprovante_pesquisa", label: "Relatório de Pesquisa Completo *", meios: ["IP", "PQ"], accept: ".pdf,.xlsx,.xls" },
    { name: "comprovante_locacao", label: "Contrato + Nota Fiscal *", meios: ["LO"], accept: ".pdf" },
    { name: "comprovante_maladireta", label: "Relatório de Distribuição + Fotos das Peças *", meios: ["MD"], accept: "image/*,.pdf,.xlsx,.xls" },
    { name: "comprovante_gigadoor", label: "Relatório Fotográfico com Endereço (Diurno/Noturno) *", meios: ["GD"], accept: "image/*,.pdf,.zip" },
    { name: "comprovante_carrosom", label: "Relatório de Circulação + Fotos/Vídeos *", meios: ["CS"], accept: "image/*,video/*,.pdf,.zip" },
    { name: "comprovante_criacao", label: "Relatório de Atividades / Arquivos Criados *", meios: ["RL", "CR"], accept: ".pdf,image/*,.zip" },
    { name: "comprovante_fidelidade", label: "Relatório de Participantes + Documentação *", meios: ["FI"], accept: ".pdf,.xlsx,.xls,image/*" },
    { name: "comprovante_assessoria", label: "Comprovante de Assessoria de Imprensa *", meios: ["AS"], accept: ".pdf,image/*,.zip" },
    { name: "comprovante_ma", label: "Comprovantes Diversos (Mídia Alternativa) *", meios: ["MA"], accept: "*" },
    { name: "comprovante_outros", label: "Comprovantes Diversos *", meios: ["OU", "TO"], accept: "*" },
];
